    Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.
    

In [15]:
import numpy as np

A = np.array([[11, 2,3 ], [15, 13, 4]])
B = np.array([[1, 2, 3],[3,2,1]])
vert = np.concatenate([A,B],axis = 0)
vert

array([[11,  2,  3],
       [15, 13,  4],
       [ 1,  2,  3],
       [ 3,  2,  1]])

   
    Find common elements between A and B. [Hint : Intersection of two sets]

In [35]:
set(A.flatten()).intersection(set(B.flatten()))


{2, 3}

    Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [48]:
lower = 1
upper = 10

A0 = A[np.where(A>lower)]
A0[np.where(A0<upper)]

array([2, 3, 4])

    Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [49]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [9]:

horz = np.concatenate([A,B],axis =1)
horz

array([[1, 2, 3, 1, 2, 3],
       [5, 3, 4, 3, 2, 1]])


Practice Questions for Pandas

    From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

    Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

    How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))



In [2]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')